baseWeight = "tri*weight*puweight*mueffweight*eleffweight"
baseWeightNOPU = "tri*weight*mueffweight*eleffweight"
mceventweight=[
#{"name":"CEN",       "tree":"nom2",    "var":"("+baseWeight+")"},
#{"name":"NoPU",      "tree":"nom2",    "var":"("+baseWeightNOPU+")"},
{"name":"csvweight", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"PU_Up",     "tree":"nom2",    "var":"(tri*weight*puweightUp*mueffweight*eleffweight*csvweights2[0])"},
{"name":"PU_Down",   "tree":"nom2",    "var":"(tri*weight*puweightDown*mueffweight*eleffweight*csvweights2[0])"},
{"name":"JER_Up",    "tree":"nomJER_up",   "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JER_Down",  "tree":"nomJER_dw",   "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"JES_Up",    "tree":"nomJES_up",   "var":"("+baseWeight+"*csvweights2[1])"},        
#{"name":"JES_Down",  "tree":"nomJES_dw",   "var":"("+baseWeight+"*csvweights2[2])"},      
{"name":"Btag_LF_Up",     "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[3])"},         
{"name":"Btag_LF_Down",   "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[4])"},       
#]
#=[
{"name":"Btag_HF_Up",           "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[5])"},           
{"name":"Btag_HF_Down",         "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[6])"},         
{"name":"Btag_HF_Stats1_Up",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[7])"},    
{"name":"Btag_HF_Stats1_Down",  "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[8])"},  
{"name":"Btag_HF_Stats2_Up",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[9])"},    
{"name":"Btag_HF_Stats2_Down",  "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[10])"},  
{"name":"Btag_LF_Stats1_Up",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[11])"},    
{"name":"Btag_LF_Stats1_Down",  "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[12])"},  
{"name":"Btag_LF_Stats2_Up",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[13])"},    
{"name":"Btag_LF_Stats2_Down",  "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[14])"},  
{"name":"Btag_CQ_Err1_Up",      "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[15])"},   
{"name":"Btag_CQ_Err1_Down",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[16])"}, 
{"name":"Btag_CQ_Err2_Up",      "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[17])"},   
{"name":"Btag_CQ_Err2_Down",    "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[18])"},
#]
#mceventweight=[
{"name":"Mu_Eff_Up",     "tree":"nom2",    "var":"(tri*weight*puweight*mueffweight_up*eleffweight*csvweights2[0])"},
{"name":"Mu_Eff_Down",   "tree":"nom2",    "var":"(tri*weight*puweight*mueffweight_dn*eleffweight*csvweights2[0])"},
{"name":"El_Eff_Up",     "tree":"nom2",    "var":"(tri*weight*puweight*mueffweight*eleffweight_up*csvweights2[0])"},
{"name":"El_Eff_Down",   "tree":"nom2",    "var":"(tri*weight*puweight*mueffweight*eleffweight_dn*csvweights2[0])"},

#{"name":"Mu_Scale_Up",     "tree":"nomMu_up",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"Mu_Scale_Down",     "tree":"nomMu_dw",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"El_Scale_Up",     "tree":"nomEl_up",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"El_Scale_Down",     "tree":"nomEl_dw",    "var":"("+baseWeight+"*csvweights2[0])"},

{"name":"Trigger_Up",   "tree":"nom2",        "var": "(weight*puweight*mueffweight*eleffweight*tri_up*csvweights2[0])"},
{"name":"Trigger_Down", "tree":"nom2",        "var": "(weight*puweight*mueffweight*eleffweight*tri_dn*csvweights2[0])"},
#{"name":"Free_ttbj", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"Ttcc_Fraction_Fit_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"Ttcc_Fraction_Fit_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"Ttcc_Fraction_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"Ttcc_Fraction_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"topPt_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*topPtWeight)"},
{"name":"topPt_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"FSR_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"FSR_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"ISR_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"ISR_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"UE_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"UE_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"hdamp_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"hdamp_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"qcderdon_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"qcderdon_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"erdon_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"erdon_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"gluonmove_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"gluonmove_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"MuF_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsUp[0])"},
{"name":"MuR_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsUp[1])"},
#{"name":"MuR_MuF_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsUp[2])"},
{"name":"MuF_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsDown[0])"},
{"name":"MuR_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsDown[1])"},
#{"name":"MuR_MuF_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*scaleWeightsDown[2])"},
{"name":"PDF_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*pdfWeights[0])"},
{"name":"PDF_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*pdfWeights[1])"},
{"name":"PDFAlphaS_Up", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*pdfWeights[2])"},
{"name":"PDFAlphaS_Down", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0]*pdfWeights[3])"},
{"name":"JES_AbsoluteStat_Up", "tree":"JES_AbsoluteStat_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteStat_Down", "tree":"JES_AbsoluteStat_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteScale_Up", "tree":"JES_AbsoluteScale_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteScale_Down", "tree":"JES_AbsoluteScale_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteMPFBias_Up", "tree":"JES_AbsoluteMPFBias_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteMPFBias_Down", "tree":"JES_AbsoluteMPFBias_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_Fragmentation_Up", "tree":"JES_Fragmentation_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_Fragmentation_Down", "tree":"JES_Fragmentation_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionECAL_Up", "tree":"JES_SinglePionECAL_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionECAL_Down", "tree":"JES_SinglePionECAL_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionHCAL_Up", "tree":"JES_SinglePionHCAL_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionHCAL_Down", "tree":"JES_SinglePionHCAL_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_FlavorQCD_Up", "tree":"JES_FlavorQCD_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_FlavorQCD_Down", "tree":"JES_FlavorQCD_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_TimePtEta_Up", "tree":"JES_TimePtEta_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_TimePtEta_Down", "tree":"JES_TimePtEta_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC1_Up", "tree":"JES_RelativeJEREC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC1_Down", "tree":"JES_RelativeJEREC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC2_Up", "tree":"JES_RelativeJEREC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC2_Down", "tree":"JES_RelativeJEREC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJERHF_Up", "tree":"JES_RelativeJERHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJERHF_Down", "tree":"JES_RelativeJERHF_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtBB_Up", "tree":"JES_RelativePtBB_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtBB_Down", "tree":"JES_RelativePtBB_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC1_Up", "tree":"JES_RelativePtEC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC1_Down", "tree":"JES_RelativePtEC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC2_Up", "tree":"JES_RelativePtEC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC2_Down", "tree":"JES_RelativePtEC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtHF_Up", "tree":"JES_RelativePtHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtHF_Down", "tree":"JES_RelativePtHF_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeBal_Up", "tree":"JES_RelativeBal_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeBal_Down", "tree":"JES_RelativeBal_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeFSR_Up", "tree":"JES_RelativeFSR_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeFSR_Down", "tree":"JES_RelativeFSR_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpDataMC_Up", "tree":"JES_PileUpDataMC_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpDataMC_Down", "tree":"JES_PileUpDataMC_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtRef_Up", "tree":"JES_PileUpPtRef_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtRef_Down", "tree":"JES_PileUpPtRef_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtBB_Up", "tree":"JES_PileUpPtBB_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtBB_Down", "tree":"JES_PileUpPtBB_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC1_Up", "tree":"JES_PileUpPtEC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC1_Down", "tree":"JES_PileUpPtEC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC2_Up", "tree":"JES_PileUpPtEC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC2_Down", "tree":"JES_PileUpPtEC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtHF_Up", "tree":"JES_PileUpPtHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtHF_Down", "tree":"JES_PileUpPtHF_dw", "var":"("+baseWeight+"*csvweights2[0])"}
#{"name":"TT_powheg_herwig", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"},
#{"name":"TT_aMC", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"}
#{"name":"TT_powheg_evtgen", "tree":"nom2",    "var":"("+baseWeight+"*csvweights2[0])"}
]

#mceventweightMG5 = [{'name':i['name'],'var':i['var'].replace("(weight*","(").replace('*weight*','*')} for i in mceventweight]
