baseWeight = "tri*weight*puweight*mueffweight*eleffweight"
baseWeightNOPU = "tri*weight*mueffweight*eleffweight"
mceventweight=[
{"name":"JES_AbsoluteStat_Up", "tree":"JES_AbsoluteStat_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteStat_Down", "tree":"JES_AbsoluteStat_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteScale_Up", "tree":"JES_AbsoluteScale_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteScale_Down", "tree":"JES_AbsoluteScale_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteMPFBias_Up", "tree":"JES_AbsoluteMPFBias_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_AbsoluteMPFBias_Down", "tree":"JES_AbsoluteMPFBias_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_Fragmentation_Up", "tree":"JES_Fragmentation_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_Fragmentation_Down", "tree":"JES_Fragmentation_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionECAL_Up", "tree":"JES_SinglePionECAL_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionECAL_Down", "tree":"JES_SinglePionECAL_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionHCAL_Up", "tree":"JES_SinglePionHCAL_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_SinglePionHCAL_Down", "tree":"JES_SinglePionHCAL_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_FlavorQCD_Up", "tree":"JES_FlavorQCD_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_FlavorQCD_Down", "tree":"JES_FlavorQCD_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_TimePtEta_Up", "tree":"JES_TimePtEta_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_TimePtEta_Down", "tree":"JES_TimePtEta_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC1_Up", "tree":"JES_RelativeJEREC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC1_Down", "tree":"JES_RelativeJEREC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC2_Up", "tree":"JES_RelativeJEREC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJEREC2_Down", "tree":"JES_RelativeJEREC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJERHF_Up", "tree":"JES_RelativeJERHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeJERHF_Down", "tree":"JES_RelativeJERHF_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtBB_Up", "tree":"JES_RelativePtBB_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtBB_Down", "tree":"JES_RelativePtBB_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC1_Up", "tree":"JES_RelativePtEC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC1_Down", "tree":"JES_RelativePtEC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC2_Up", "tree":"JES_RelativePtEC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtEC2_Down", "tree":"JES_RelativePtEC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtHF_Up", "tree":"JES_RelativePtHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativePtHF_Down", "tree":"JES_RelativePtHF_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeBal_Up", "tree":"JES_RelativeBal_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeBal_Down", "tree":"JES_RelativeBal_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeFSR_Up", "tree":"JES_RelativeFSR_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_RelativeFSR_Down", "tree":"JES_RelativeFSR_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpDataMC_Up", "tree":"JES_PileUpDataMC_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpDataMC_Down", "tree":"JES_PileUpDataMC_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtRef_Up", "tree":"JES_PileUpPtRef_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtRef_Down", "tree":"JES_PileUpPtRef_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtBB_Up", "tree":"JES_PileUpPtBB_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtBB_Down", "tree":"JES_PileUpPtBB_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC1_Up", "tree":"JES_PileUpPtEC1_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC1_Down", "tree":"JES_PileUpPtEC1_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC2_Up", "tree":"JES_PileUpPtEC2_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtEC2_Down", "tree":"JES_PileUpPtEC2_dw", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtHF_Up", "tree":"JES_PileUpPtHF_up", "var":"("+baseWeight+"*csvweights2[0])"},
{"name":"JES_PileUpPtHF_Down", "tree":"JES_PileUpPtHF_dw", "var":"("+baseWeight+"*csvweights2[0])"}

]

#mceventweightMG5 = [{'name':i['name'],'var':i['var'].replace("(weight*","(").replace('*weight*','*')} for i in mceventweight]
